var CasesSeedApril = [
  {'id': '0001', 'case_number': 'G109487874', 'hearing_date':'2015-06-16', 'hearing_type':'FV', 'parties': ['(POL) Police Officer 1','Joe Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0002', 'case_number': 'G159550863', 'hearing_date':'2015-06-16', 'hearing_type':'APPL', 'parties': ['(POL) Police Officer 3','Sue Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0003', 'case_number': 'F144987884', 'hearing_date':'2015-06-16', 'hearing_type':'FV', 'parties': ['(POL) Police Officer 3','Craig Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0004', 'case_number': 'G104995875', 'hearing_date':'2015-06-16', 'hearing_type':'APPL', 'parties': ['(POL) Police Officer 2','Claire Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0005', 'case_number': 'F104995893', 'hearing_date':'2015-06-16', 'hearing_type':'APPL', 'parties': ['(POL) Police Officer 1','Alice Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0006', 'case_number': 'G104345875', 'hearing_date':'2015-06-16', 'hearing_type':'FV', 'parties': ['(POL) Police Officer 1','Phil Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0007', 'case_number': 'G124435808', 'hearing_date':'2015-06-16', 'hearing_type':'PSIO', 'parties': ['(POL) Police Officer 2','Bob Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0008', 'case_number': 'F156587572', 'hearing_date':'2015-06-16', 'hearing_type':'PSIO', 'parties': ['(POL) Police Officer 2','Chelsea Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0009', 'case_number': 'F456973857', 'hearing_date':'2015-06-16', 'hearing_type':'PSIO', 'parties': ['(POL) Police Officer 1','Phil Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
];

var CasesSeedLatest = [
  {'list_number': 1, 'hearing_date':'2016-05-09', 'case_number': 'G10747253', 'parties': [{'name': '(POL) Atkinson, Tenneille'}, {'name': 'A, Nguyen, Loan'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 2, 'hearing_date':'2016-05-09', 'case_number': 'G10801177', 'parties': [{'name': '(POL) Rinaldi, Susan'}, {'name': 'Rinaldi, James B'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 3, 'hearing_date':'2016-05-09', 'case_number': 'F10140443', 'parties': [{'name': 'Agrapidis, Antonis'}, {'name': 'Sargedis, Peggy'}], 'hearing_type': 'APPL', 'matter': 'Family Violence'},
  {'list_number': 4, 'hearing_date':'2016-05-09', 'case_number': 'G11046381', 'parties': [{'name': 'Bisangana, Beatrice, M'}, {'name': 'Gibson, Helen'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 5, 'hearing_date':'2016-05-09', 'case_number': 'F14022335', 'parties': [{'name': 'Deng Achok'}, {'name': 'John, Issac'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Varia'},
  {'list_number': 6, 'hearing_date':'2016-05-09', 'case_number': 'G10931490', 'parties': [{'name': 'Daniel, Nicole'}, {'name': 'Condos, Ian'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 7, 'hearing_date':'2016-05-09', 'case_number': 'G11009350', 'parties': [{'name': 'Davids, Nathalie'}, {'name': 'Stevenson, Joseph'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 9, 'hearing_date':'2016-05-09', 'case_number': 'G11086176', 'parties': [{'name': 'Garrick, Clea'}, {'name': 'Gosper, Linsey'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 10, 'hearing_date':'2016-05-09', 'case_number': 'G10682089', 'parties': [{'name': 'Giannaras, Christopher, G'}, {'name': 'Mccullough, Peter'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 11, 'hearing_date':'2016-05-09', 'case_number': 'G11143115', 'parties': [{'name': 'Gosper, Linsey'}, {'name': 'Garrick, Clea'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 12, 'hearing_date':'2016-05-09', 'case_number': 'G11143206', 'parties': [{'name': 'Gosper, Linsey'}, {'name': 'Mason, Benjamin'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 13, 'hearing_date':'2016-05-09', 'case_number': 'G10914125', 'parties': [{'name': 'Greco, Giuseppe'}, {'name': 'Greco, Gaetano'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 14, 'hearing_date':'2016-05-09', 'case_number': 'F10140443', 'parties': [{'name': 'Sagredis, Peggy'}, {'name': 'Agrapidis, Antonios'}], 'hearing_type': 'APPL', 'matter': 'APPL, Ap. for Exten'},
  {'list_number': 15, 'hearing_date':'2016-05-09', 'case_number': 'G11076962', 'parties': [{'name': 'Jones, Simon P'}, {'name': 'Stein, Grant'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 16, 'hearing_date':'2016-05-09', 'case_number': 'G10466680', 'parties': [{'name': 'Koutroumbalos, Anthoula'}, {'name': 'Papageorgiou, Kosta'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Revoca'},
  {'list_number': 17, 'hearing_date':'2016-05-09', 'case_number': 'G11076088', 'parties': [{'name': 'Langdon, Molly-Rose'}, {'name': 'Stein, Grant'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 18, 'hearing_date':'2016-05-09', 'case_number': 'G11008878', 'parties': [{'name': 'Li, Jing Y'}, {'name': 'Lee, Joseph'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 19, 'hearing_date':'2016-05-09', 'case_number': 'G11009383', 'parties': [{'name': 'Li, Jing'}, {'name': 'Lee, Joseph'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 20, 'hearing_date':'2016-05-09', 'case_number': 'G11086438', 'parties': [{'name': 'Mason, Benjamin'}, {'name': 'Gosper, Linsey'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 21, 'hearing_date':'2016-05-09', 'case_number': 'G11116770', 'parties': [{'name': 'Mohamed, Mohamud'}, {'name': 'Farah, Ubah A'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 22, 'hearing_date':'2016-05-09', 'case_number': 'G11052781', 'parties': [{'name': 'Oborn, Angela'}, {'name': 'Karaman, Cigdem'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 23, 'hearing_date':'2016-05-09', 'case_number': 'F10515357', 'parties': [{'name': 'Read, Margaret J'}, {'name': 'Parisi, Andrew'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Exten'},
  {'list_number': 24, 'hearing_date':'2016-05-09', 'case_number': 'F13182491', 'parties': [{'name': 'Slade, Kylie L'}, {'name': 'Hampton, Scott'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Varia'},
  {'list_number': 25, 'hearing_date':'2016-05-09', 'case_number': 'G11147721', 'parties': [{'name': 'Waters, Stephanie'}, {'name': 'Cochrane-NG, Nicholas'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 26, 'hearing_date':'2016-05-09', 'case_number': 'G10275652', 'parties': [{'name': 'Wilson, Arabella'}, {'name': 'Phung, Phuc A'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 27, 'hearing_date':'2016-05-09', 'case_number': 'G11100330', 'parties': [{'name': 'Zhong, Xu Pu'}, {'name': 'Yang, Xiao Ran'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 28, 'hearing_date':'2016-05-09', 'case_number': 'F13532766', 'parties': [{'name': '(POL) Clarke, Cody'}, {'name': 'Thomas, Danielle'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 29, 'hearing_date':'2016-05-09', 'case_number': 'D12541840', 'parties': [{'name': 'Denehey, Cathy'}, {'name': 'O\'Regan, Alexander'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Varia'},
  {'list_number': 30, 'hearing_date':'2016-05-09', 'case_number': 'F12479235', 'parties': [{'name': 'Spano, Anna'}, {'name': 'Acar, Ayhan'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 31, 'hearing_date':'2016-05-09', 'case_number': 'G11196906', 'parties': [{'name': 'Loan, Nguyen'}, {'name': 'Atkinson, Tenneille'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 32, 'hearing_date':'2016-05-09', 'case_number': 'G11196961', 'parties': [{'name': 'Nguyen, Loan'}, {'name': 'Morgan, Travis'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 33, 'hearing_date':'2016-05-09', 'case_number': 'G11175136', 'parties': [{'name': 'Yang, Xiao Ran'}, {'name': 'Zhong, Xu Pu'}], 'hearing_type': 'FV', 'matter': 'Family Violence'}
];

var CasesSeedJune06 = [
  {"list_number": "1", "matter": "Personal Safety Intervention Order", "case_number": "G11019981", "hearing_date":"2016-06-06", "hearing_type":"PSIO", "parties": [{'name': "(POL) Clohesy, Blair"},{'name': "Byrne, Dwayne"}]},
  {"list_number": "2", "matter": "Family Violence", "case_number": "G10216029", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Guled, Amran"},{'name': "Osman, Aynan M"}]},
  {"list_number": "3", "matter": "Family Violence", "case_number": "G10749625", "hearing_date":"2016-06-06", "hearing_type":"APPL", "parties": [{'name': "(POL) Koutras, Vivi"},{'name': "Al-Kufy, Firas"}]},
  {"list_number": "4", "matter": "Ap. For Variation", "case_number": "G11047862", "hearing_date":"2016-06-06", "hearing_type":"APPL", "parties": [{'name': "(POL) Rooks, Melissa"},{'name': "Giannioudis, Zoe"}]},
  {"list_number": "5", "matter": "Family Violence", "case_number": "G10519748", "hearing_date":"2016-06-06", "hearing_type":"APPL", "parties": [{'name': "(POL) Rooks, Melissa"},{'name': "Giannioudis, Zoe"}]},
  {"list_number": "6", "matter": "Family Violence", "case_number": "F12479235", "hearing_date":"2016-06-06", "hearing_type":"APPL", "parties": [{'name': "(POL) Spano, Anna"},{'name': "Acar, Ayhan"}]},
  {"list_number": "7", "matter": "Family Violence", "case_number": "G11287656", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Tse, Sarah"},{'name': "Tse, Allen"}]},
  {"list_number": "8", "matter": "Ap. For Variation", "case_number": "F12479235", "hearing_date":"2016-06-06", "hearing_type":"Appl", "parties": [{'name': "Acar, Ayhan"},{'name': "Spano, Anna"}]},
  {"list_number": "9", "matter": "Family Violence", "case_number": "G11159373", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "Ahmed, Rowda"},{'name': "Aden, Said"}]},
  {"list_number": "10", "matter": "Personal Safety Intervention Order", "case_number": "G11309230", "hearing_date":"2016-06-06", "hearing_type":"PSIO", "parties": [{'name': "Burns, Latham D"},{'name': "Cayli, Sinan"}]},
  {"list_number": "11", "matter": "Family Violence", "case_number": "G11406267", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "Evans, Mikaelie Aysha"}, {'name': "Lewis, James Eion Ard"}]},
  {"list_number": "12", "matter": "Personal Safety Intervention Order", "case_number": "G11086176", "hearing_date":"2016-06-06", "hearing_type":"PSIO", "parties": [{'name': "Garrick, Clea"},{'name': "Gosper, Linsey"}]},
  {"list_number": "13", "matter": "Personal Safety Intervention Order", "case_number": "G11143115", "hearing_date":"2016-06-06", "hearing_type":"PSIO", "parties": [{'name': "Gosper, Linsey"},{'name': "Garrick, Clea"}]},
  {"list_number": "14", "matter": "Personal Safety Intervention Order", "case_number": "G11143206", "hearing_date":"2016-06-06", "hearing_type":"PSIO", "parties": [{'name': "Gosper, Linsey"},{'name': "Mason, Benjamin"}]},
  {"list_number": "15", "matter": "Ap. for Revocation", "case_number": "G10216029", "hearing_date":"2016-06-06", "hearing_type":"APPL", "parties": [{'name': "Guled, Amran"},{'name': "Osman, Aynan M"}]},
  {"list_number": "16", "matter": "Family Violence", "case_number": "G11439656", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "Hollins, Jacob"},{'name': "Devcich, Alyse"}]},
  {"list_number": "17", "matter": "Personal Safety Intervention Order", "case_number": "G11076962", "hearing_date":"2016-06-06", "hearing_type":"PSIO", "parties": [{'name': "Jones, Simon P"},{'name': "Stein, Grant"}]},
  {"list_number": "18", "matter": "Family Violence", "case_number": "G11076088", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "Langdon, Molly-Rose"},{'name': "Stein, Grant"}]},
  {"list_number": "19", "matter": "Family Violence", "case_number": "G11367973", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "Lestrange, Amanda"},{'name': "Egglestone, Aaron"}]},
  {"list_number": "20", "matter": "Personal Safety Intervention Order", "case_number": "G11086438", "hearing_date":"2016-06-06", "hearing_type":"PSIO", "parties": [{'name': "Mason, Benjamin"},{'name': "Gosper, Linsey"}]},
  {"list_number": "21", "matter": "Family Violence", "case_number": "G11350846", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "Reiter, Kristen"},{'name': "Taylor, Michael"}]},
  {"list_number": "22", "matter": "Family Violence", "case_number": "G11238744", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "Shapartanis, Paul"},{'name': "Shapartanis, Elizabeth"}]},
  {"list_number": "23", "matter": "Ap. For Variation", "case_number": "G10261402", "hearing_date":"2016-06-06", "hearing_type":"PSIO", "parties": [{'name': "(POL) Mackog, Alval"},{'name': "Akot, Fasco"}]},
  {"list_number": "24", "matter": "Personal Safety Intervention Order", "case_number": "G11498918", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Delaney, Corey"},{'name': "Fontane, Mark"}]},
  {"list_number": "25", "matter": "Personal Safety Intervention Order", "case_number": "G11337632", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "Omar, Mohamed"},{'name': "Hammond, Anthony"}]},
  {"list_number": "26", "matter": "Family Violence", "case_number": "G11501536", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Culhane, Lisa"},{'name': "Merry, David"}]},
  {"list_number": "27", "matter": "Ap. For Variation", "case_number": "G11092088", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Garoni, Jay"},{'name': "Millman, Kate"}]},
  {"list_number": "28", "matter": "Family Violence", "case_number": "", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Gomez, Rachel"},{'name': "Naidu, Jasuhta"}]},
  {"list_number": "29", "matter": "Family Violence", "case_number": "", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Tossoun, Amy"},{'name': "Tossoun Fady"}]},
  {"list_number": "30", "matter": "Family Violence", "case_number": "", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Mohr, Joel"},{'name': "Mohr, Yukan"}]},
  {"list_number": "31", "matter": "Personal Safety Intervention Order", "case_number": "", "hearing_date":"2016-06-06", "hearing_type":"FV", "parties": [{'name': "(POL) Seddon, Jodie"},{'name': "Warren, Allen"}]}
];


module.exports = CasesSeedJune06;
