var CasesSeedApril = [
  {'id': '0001', 'case_number': 'G109487874', 'hearing_date':'2015-06-16', 'hearing_type':'FV', 'parties': ['(POL) Police Officer 1','Joe Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0002', 'case_number': 'G159550863', 'hearing_date':'2015-06-16', 'hearing_type':'APPL', 'parties': ['(POL) Police Officer 3','Sue Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0003', 'case_number': 'F144987884', 'hearing_date':'2015-06-16', 'hearing_type':'FV', 'parties': ['(POL) Police Officer 3','Craig Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0004', 'case_number': 'G104995875', 'hearing_date':'2015-06-16', 'hearing_type':'APPL', 'parties': ['(POL) Police Officer 2','Claire Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0005', 'case_number': 'F104995893', 'hearing_date':'2015-06-16', 'hearing_type':'APPL', 'parties': ['(POL) Police Officer 1','Alice Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0006', 'case_number': 'G104345875', 'hearing_date':'2015-06-16', 'hearing_type':'FV', 'parties': ['(POL) Police Officer 1','Phil Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0007', 'case_number': 'G124435808', 'hearing_date':'2015-06-16', 'hearing_type':'PSIO', 'parties': ['(POL) Police Officer 2','Bob Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0008', 'case_number': 'F156587572', 'hearing_date':'2015-06-16', 'hearing_type':'PSIO', 'parties': ['(POL) Police Officer 2','Chelsea Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
  {'id': '0009', 'case_number': 'F456973857', 'hearing_date':'2015-06-16', 'hearing_type':'PSIO', 'parties': ['(POL) Police Officer 1','Phil Bloggs'], 'outcomes': null, 'interactions': [], 'conflicts': []},
];

var CasesSeedLatest = [
  {'list_number': 1, 'hearing_date':'2016-05-09', 'case_number': 'G10747253', 'parties': [{'name': '(POL) Atkinson, Tenneille'}, {'name': 'A, Nguyen, Loan'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 2, 'hearing_date':'2016-05-09', 'case_number': 'G10801177', 'parties': [{'name': '(POL) Rinaldi, Susan'}, {'name': 'Rinaldi, James B'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 3, 'hearing_date':'2016-05-09', 'case_number': 'F10140443', 'parties': [{'name': 'Agrapidis, Antonis'}, {'name': 'Sargedis, Peggy'}], 'hearing_type': 'APPL', 'matter': 'Family Violence'},
  {'list_number': 4, 'hearing_date':'2016-05-09', 'case_number': 'G11046381', 'parties': [{'name': 'Bisangana, Beatrice, M'}, {'name': 'Gibson, Helen'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 5, 'hearing_date':'2016-05-09', 'case_number': 'F14022335', 'parties': [{'name': 'Deng Achok'}, {'name': 'John, Issac'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Varia'},
  {'list_number': 6, 'hearing_date':'2016-05-09', 'case_number': 'G10931490', 'parties': [{'name': 'Daniel, Nicole'}, {'name': 'Condos, Ian'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 7, 'hearing_date':'2016-05-09', 'case_number': 'G11009350', 'parties': [{'name': 'Davids, Nathalie'}, {'name': 'Stevenson, Joseph'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 9, 'hearing_date':'2016-05-09', 'case_number': 'G11086176', 'parties': [{'name': 'Garrick, Clea'}, {'name': 'Gosper, Linsey'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 10, 'hearing_date':'2016-05-09', 'case_number': 'G10682089', 'parties': [{'name': 'Giannaras, Christopher, G'}, {'name': 'Mccullough, Peter'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 11, 'hearing_date':'2016-05-09', 'case_number': 'G11143115', 'parties': [{'name': 'Gosper, Linsey'}, {'name': 'Garrick, Clea'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 12, 'hearing_date':'2016-05-09', 'case_number': 'G11143206', 'parties': [{'name': 'Gosper, Linsey'}, {'name': 'Mason, Benjamin'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 13, 'hearing_date':'2016-05-09', 'case_number': 'G10914125', 'parties': [{'name': 'Greco, Giuseppe'}, {'name': 'Greco, Gaetano'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 14, 'hearing_date':'2016-05-09', 'case_number': 'F10140443', 'parties': [{'name': 'Sagredis, Peggy'}, {'name': 'Agrapidis, Antonios'}], 'hearing_type': 'APPL', 'matter': 'APPL, Ap. for Exten'},
  {'list_number': 15, 'hearing_date':'2016-05-09', 'case_number': 'G11076962', 'parties': [{'name': 'Jones, Simon P'}, {'name': 'Stein, Grant'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 16, 'hearing_date':'2016-05-09', 'case_number': 'G10466680', 'parties': [{'name': 'Koutroumbalos, Anthoula'}, {'name': 'Papageorgiou, Kosta'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Revoca'},
  {'list_number': 17, 'hearing_date':'2016-05-09', 'case_number': 'G11076088', 'parties': [{'name': 'Langdon, Molly-Rose'}, {'name': 'Stein, Grant'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 18, 'hearing_date':'2016-05-09', 'case_number': 'G11008878', 'parties': [{'name': 'Li, Jing Y'}, {'name': 'Lee, Joseph'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 19, 'hearing_date':'2016-05-09', 'case_number': 'G11009383', 'parties': [{'name': 'Li, Jing'}, {'name': 'Lee, Joseph'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 20, 'hearing_date':'2016-05-09', 'case_number': 'G11086438', 'parties': [{'name': 'Mason, Benjamin'}, {'name': 'Gosper, Linsey'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 21, 'hearing_date':'2016-05-09', 'case_number': 'G11116770', 'parties': [{'name': 'Mohamed, Mohamud'}, {'name': 'Farah, Ubah A'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 22, 'hearing_date':'2016-05-09', 'case_number': 'G11052781', 'parties': [{'name': 'Oborn, Angela'}, {'name': 'Karaman, Cigdem'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 23, 'hearing_date':'2016-05-09', 'case_number': 'F10515357', 'parties': [{'name': 'Read, Margaret J'}, {'name': 'Parisi, Andrew'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Exten'},
  {'list_number': 24, 'hearing_date':'2016-05-09', 'case_number': 'F13182491', 'parties': [{'name': 'Slade, Kylie L'}, {'name': 'Hampton, Scott'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Varia'},
  {'list_number': 25, 'hearing_date':'2016-05-09', 'case_number': 'G11147721', 'parties': [{'name': 'Waters, Stephanie'}, {'name': 'Cochrane-NG, Nicholas'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 26, 'hearing_date':'2016-05-09', 'case_number': 'G10275652', 'parties': [{'name': 'Wilson, Arabella'}, {'name': 'Phung, Phuc A'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 27, 'hearing_date':'2016-05-09', 'case_number': 'G11100330', 'parties': [{'name': 'Zhong, Xu Pu'}, {'name': 'Yang, Xiao Ran'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 28, 'hearing_date':'2016-05-09', 'case_number': 'F13532766', 'parties': [{'name': '(POL) Clarke, Cody'}, {'name': 'Thomas, Danielle'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 29, 'hearing_date':'2016-05-09', 'case_number': 'D12541840', 'parties': [{'name': 'Denehey, Cathy'}, {'name': 'O\'Regan, Alexander'}], 'hearing_type': 'APPL', 'matter': 'Ap. for Varia'},
  {'list_number': 30, 'hearing_date':'2016-05-09', 'case_number': 'F12479235', 'parties': [{'name': 'Spano, Anna'}, {'name': 'Acar, Ayhan'}], 'hearing_type': 'FV', 'matter': 'Family Violence'},
  {'list_number': 31, 'hearing_date':'2016-05-09', 'case_number': 'G11196906', 'parties': [{'name': 'Loan, Nguyen'}, {'name': 'Atkinson, Tenneille'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 32, 'hearing_date':'2016-05-09', 'case_number': 'G11196961', 'parties': [{'name': 'Nguyen, Loan'}, {'name': 'Morgan, Travis'}], 'hearing_type': 'PSIO', 'matter': 'Personal Safety Intervention Order'},
  {'list_number': 33, 'hearing_date':'2016-05-09', 'case_number': 'G11175136', 'parties': [{'name': 'Yang, Xiao Ran'}, {'name': 'Zhong, Xu Pu'}], 'hearing_type': 'FV', 'matter': 'Family Violence'}
];

module.exports = CasesSeedLatest;
